[platformio]
default_envs = cardputer_adv

[env:cardputer_adv]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/m5stack/M5GFX.git
  https://github.com/m5stack/M5Unified.git
  https://github.com/Arduino-IRremote/Arduino-IRremote.git
  https://github.com/m5stack/M5Cardputer.git#2d4fa66
  https://github.com/bblanchon/ArduinoJson.git
build_flags =
  -D CARDPUTER_LAUNCHER_VERSION=\"0.3.0\"
  -D CARDPUTER_LAUNCHER_REPO=\"https://github.com/yottayoshida/cardputer-launcher-sdk\"
  -D ARDUINO_USB_CDC_ON_BOOT=1
